### ISSUE TITLE
Nexus Integration is not available Talend Communicty Edition 8 ?

### ISSUE THREAD

**Issue by aliridha1510** [jlolling/talendcomp_tNexusDeploy#1]
![Screenshot from 2022-11-21 15-12-51](https://user-images.githubusercontent.com/23260197/203076376-56bbb57e-b232-454b-bbfa-1f37410b53bb.png)

**Comment by jlolling** [comment]
Hi Ali,

This is NOT the right way to import custom components!

Please take a look here: https://jan-lolling.de/talend/howtos/install_components/how-to-install-talend-custom-components.html <https://jan-lolling.de/talend/howtos/install_components/how-to-install-talend-custom-components.html>

Best regards
Jan
